version: '3.8'

services:
  redis:
    image: "redis:7-alpine"
    container_name: movieapi-redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: movieapi-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__Connection=redis:6379
      - Tmdb__ApiKey=${TMDB_API_KEY}
    depends_on:
      - redis
